//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 使用者 RemoveDuplicate.rc

#define IDS_APP_TITLE			103

// 字符串资源ID
#define IDS_FOLDER_PATH			200
#define IDS_BROWSE				201
#define IDS_SCAN_DUPLICATES		202
#define IDS_DELETE_DUPLICATES	203
#define IDS_READY				204
#define IDS_SELECT_FOLDER		205
#define IDS_NO_FILES_FOUND		206
#define IDS_SCANNING_FILES		207
#define IDS_CALCULATING_HASH	208
#define IDS_PROCESSING_FILE		209
#define IDS_NO_DUPLICATES_FOUND	210
#define IDS_FOUND_DUPLICATES	211
#define IDS_DELETING_FILES		212
#define IDS_DELETE_COMPLETE		213
#define IDS_DELETED				214
#define IDS_DELETE_FAILED		215
#define IDS_NO_DUPLICATES_TO_DELETE	216
#define IDS_CONFIRM_DELETE		217
#define IDS_SELECT_FOLDER_FIRST	218
#define IDS_LANGUAGE			219
#define IDS_LANGUAGE_NOT_IMPLEMENTED	220
#define IDS_WINDOW_TITLE		221
#define IDS_ABOUT_TITLE			222
#define IDS_VERSION				223
#define IDS_COPYRIGHT			224
#define IDS_OK					225
#define IDS_FILE				226
#define IDS_HELP				227
#define IDS_EXIT				228
#define IDS_ABOUT				229
#define IDS_LANG_CHINESE		230
#define IDS_LANG_ENGLISH		231
#define IDS_LANG_FRENCH			232
#define IDS_LANG_RUSSIAN		233
#define IDS_LANG_ARABIC			234
#define IDS_LANG_SPANISH		235
#define IDS_COLUMN_FILE			236
#define IDS_COLUMN_PATH			237
#define IDS_GROUP_HEADER		238
#define IDS_DUPLICATE_GROUP		239
#define IDC_STATIC_CAPTION		240
#define IDC_LIST_DUPLICATES		241
#define IDM_SELECT_ALL			242
#define IDM_DESELECT_ALL		243
#define IDC_STATIC_FOLDER		244
#define IDC_BTN_BROWSE			245
#define IDC_BTN_SCAN			246
#define IDC_BTN_DELETE			247
#define IDC_BTN_SELECT_ALL		248
#define IDC_BTN_DESELECT_ALL	249
#define IDM_FILTER_SETTINGS		250
#define IDM_RESET_FILTERS		251

// 新增过滤对话框相关字符串ID
#define IDS_GROUPBOX_SIZE		252
#define IDS_STATIC_MIN			253
#define IDS_STATIC_MAX			254
#define IDS_GROUPBOX_TYPE		255
#define IDS_GROUPBOX_DATE		256
#define IDS_STATIC_FROM			257
#define IDS_STATIC_TO			258
#define IDS_GROUPBOX_PATH		259
#define IDS_BTN_RESET			260
#define IDS_BTN_APPLY			261

// 过滤对话框字符串资源ID
#define IDS_FILTER_DIALOG_TITLE	300
#define IDS_CHECK_SIZE_TEXT		301
#define IDS_CHECK_TYPE_TEXT		302
#define IDS_CHECK_DATE_TEXT		303
#define IDS_CHECK_PATH_TEXT		304
#define IDS_STATIC_MIN_TEXT		305
#define IDS_STATIC_MAX_TEXT		306
#define IDS_STATIC_FROM_TEXT	307
#define IDS_STATIC_TO_TEXT		308
#define IDS_GROUPBOX_SIZE_TEXT	309
#define IDS_GROUPBOX_TYPE_TEXT	310
#define IDS_GROUPBOX_DATE_TEXT	311
#define IDS_GROUPBOX_PATH_TEXT	312

#define IDR_MAINFRAME			128
#define IDD_REMOVEDUPLICATE_DIALOG	102
#define IDD_ABOUTBOX			104
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define ID_MENU_LANGUAGE		1001
#define ID_MENU_LANG_CHINESE	1002
#define ID_MENU_LANG_ENGLISH	1003
#define ID_MENU_LANG_FRENCH		1004
#define ID_MENU_LANG_RUSSIAN	1005
#define ID_MENU_LANG_ARABIC		1006
#define ID_MENU_LANG_SPANISH	1007

// 过滤菜单ID
#define ID_MENU_FILTER			1010
#define ID_MENU_FILTER_BY_SIZE	1011
#define ID_MENU_FILTER_BY_TYPE	1012
#define ID_MENU_FILTER_BY_DATE	1013
#define ID_MENU_FILTER_BY_PATH	1014
#define ID_MENU_FILTER_RESET	1015
#define ID_MENU_FILTER_SETTINGS	1016

// 过滤对话框控件ID
#define IDD_FILTER_DIALOG		1017
#define IDC_CHECK_SIZE			1018
#define IDC_CHECK_TYPE			1019
#define IDC_CHECK_DATE			1020
#define IDC_CHECK_PATH			1021
#define IDC_EDIT_MIN_SIZE		1022
#define IDC_EDIT_MAX_SIZE		1023
#define IDC_EDIT_TYPE			1024
#define IDC_EDIT_DATE_FROM		1025
#define IDC_EDIT_DATE_TO		1026
#define IDC_EDIT_PATH			1027

// 关于对话框控件ID
#define IDC_EDIT_LICENSE		1028

#define IDI_REMOVEDUPLICATE		107
#define IDI_SMALL				108
#define IDC_REMOVEDUPLICATE		109
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC			-1
#endif
